### ISSUE TITLE
Conflict Detected Even When Unchecked

### ISSUE THREAD

**Issue by rosstex** [mDibyo/berkeley-scheduler#29]
Add CS168, EE 16A. The lecture times conflict for these courses. But even if you uncheck one of the lectures (and all lab/discussions), a conflict is still reported and no schedules are generated.

**Comment by rosstex** [comment]
Actually, I now see this occurs whenever no lecture is selected for a course, so maybe that was intentional.

However, it's not that annoying because I noticed that the saved schedules feature actually saves combinations of class times that can be edited/saved and regenerated, rather than just saving a single schedule. Which is really cool! So alternate universes without a course are still technically supported.

**Comment by mDibyo** [comment]
You can now choose to completely unselect a course for schedule generation purposes!

If you unselect all sections for a course (or even all sections of a given type), the schedule generation will fail and you will be informed that you have done so.

Saving schedules has also been improved because you can now generate schedules for different sets of classes.
