### ISSUE TITLE
PE Classes show up on final scheduling

### ISSUE THREAD

**Issue by vyom-kavishwar** [mDibyo/berkeley-scheduler#35]
Even though they don't have exams (attendance based), the scheduler adds them into the finals slots based on the timings, adding more finals than you actually have

**Comment by mDibyo** [comment]
Thanks for reporting this!
Is there a specific list or department of PE classes?

**Comment by tiffanyqi** [comment]
There are some classes that will not have final exams, but are not listed anywhere currently as to whether or not there will be a final (that info will come out in October). May be good to put in the beginning message as "some of these classes may not have finals" rather than looking for each individual edge case.

**Comment by mDibyo** [comment]
@tiffanyqi That seems like the right thing to do. Will make the change.

**Comment by mDibyo** [comment]
@tiffanyqi So turns out, the API provides this information as part of the class information. So, I am just gonna use that in future.

**Comment by mDibyo** [comment]
This is now resolved in #86.
