### ISSUE TITLE
Some classes don't show up? (Possibly issue cross-listed classes)

### ISSUE THREAD

**Issue by adyotag** [mDibyo/berkeley-scheduler#37]
I can't seem to see MSE C211 when adding it to my schedule. It would be critical to fix this issue.

**Comment by mDibyo** [comment]
It is indeed due to cross-listing. The data pipeline currently queries for MSE 211, but not MSE C211, from the Student Information Systems API. The API should ideally return the class in both cases, but doesn't.

I have added a temporary fix for now. MSE C211 will show up.

I will look at potential solutions to this in future.

**Comment by tiffanyqi** [comment]
I no longer see this course.

**Comment by mDibyo** [comment]
Closing since this is for last semester (I confirmed the issue, but could not figure out why it was not showing up. )
