### ISSUE TITLE
Add a filter to remove time conflicts between sections in schedule.

### ISSUE THREAD

**Issue by mDibyo** [mDibyo/berkeley-scheduler#5]

**Comment by virajmahesh** [comment]
It's great that you support conflicting classes. But conflicting classes are rendered on top of each other, making the text hard to read (See attached image). They should appear side by side so that text is readable and it's easy to decipher the overlap.

![screen shot 2016-04-27 at 7 21 12 pm](https://cloud.githubusercontent.com/assets/779731/14873620/62630dcc-0cad-11e6-8468-f0dfe48b3876.png)

**Comment by mDibyo** [comment]
Done! :D
